---
# tasks file for ansible-role-gitlab-runner-docker/
- name: Download GitLab Runner installation script
  get_url:
    url:  https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh
    dest: ~/script.deb.sh

- name: Add GitLab Runner repository
  command: bash ~/script.deb.sh

- name: Install GitLab Runner
  apt:
    name:         gitlab-runner
    state:        latest
    update_cache: yes

- name: Ensure gitlab-runner service is started and enabled by default
  service:
    name:     gitlab-runner.service
    state:    started
    enabled:  yes

- name: Register Gitlab Runner
  command: gitlab-runner register --non-interactive --url "http://$GITLAB_SERVER_IP/" --registration-token $GITLAB_RUNNER_TOKEN --executor docker --locked=false --run-untagged=false --tag-list test --limit 0 --run-untagged=true --docker-image ubuntu:16.04 --docker-extra-hosts "$GITLAB_SERVER_FQDN:$GITLAB_SERVER_IP"
